version: '3.9'


services:
  db:
    image: postgres:15
    container_name: livraria_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3333:3333"

volumes:
  pgdata:
